### ISSUE TITLE
Application Diagnostic Tool

### ISSUE THREAD

**Issue by icrc-fdeniger** [icrc/openmrs-android-fhir#69]
A new action should be added to the main menu, allowing users to send a full application diagnostic report to the developer team. In this first version, the diagnostic data will be sent via email.
Process:
- When the user selects this action, the application will prepare a zip archive containing the relevant diagnostic information.
- The app will then automatically open the user's default email client, attaching the archive to the email, and setting the recipient to the configured support team address.
- The recipient email address will be defined by a new property: support.email.
  
The archive will include:
- Application logs.
- FHIR server URL.
- Synchronization information (as described in issue #68).

**Security important point:**
The archive will not include any patient data—only patient IDs will be included, ensuring compliance with privacy and security standards.

**Comment by parthfloyd** [comment]
## Feature Implementation: Diagnostics Zip Creation

The feature has been implemented to create & send a zip file named `diagnostics.zip`, which contains the following files:

1. **`app_logs.txt`**  
   - Contains logs as seen in Logcat in Android Studio.

2. **`SyncInfo.txt`**  
   - Provides sync information in the following format:

```
Sync Session Information
========================

FHIR Server URL: http://10.0.2.2:8080/openmrs/ws/fhir2/R4/

Last sync: 2024-12-23 12:31:47 AM

Start Time: 2024-12-19 11:36:17 PM
Downloaded Patients: 393/393
Uploaded Patients: 0/0
Completion Time: 2024-12-19 11:37:03 PM
Status: COMPLETED

Start Time: 2024-12-23 12:31:30 AM
Downloaded Patients: 393/393
Uploaded Patients: 0/0
Completion Time: 2024-12-23 12:31:47 AM
Status: COMPLETED

========================


```
